// src/utils/hexParser.ts

// Converts the hex string generated by xxd back into a binary ArrayBuffer
export const hexToArrayBuffer = (hexString: string): ArrayBuffer => {
  const cleanHex = hexString.trim().replace(/\s/g, '');
  const bytes = new Uint8Array(cleanHex.length / 2);
  
  for (let i = 0; i < cleanHex.length; i += 2) {
    bytes[i / 2] = parseInt(cleanHex.substr(i, 2), 16);
  }
  
  return bytes.buffer;
};