name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Fetch file from private repo
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        curl -H "Authorization: token $TOKEN" \
             -H "Accept: application/vnd.github.v3.raw" \
             -o _data/Ice-Cream-Master-Document.xlsm \
             -L "https://api.github.com/repos/Micbro14/MicahsCookiesAndCreamsOrderingPrivate/Ice Cream Master Document.xlsm"

    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
